Remove GitHub action .NET Core side by side hacks
It is causing this error:

```
Run SET DOTNET_31_ROOT=%DOTNET_ROOT:3.1.300=2.1.806%
  SET DOTNET_31_ROOT=%DOTNET_ROOT:3.1.300=2.1.806%
  xcopy /s /y /d %DOTNET_31_ROOT% %DOTNET_ROOT%
  shell: C:\windows\system32\cmd.EXE /D /E:ON /V:OFF /S /C "CALL "{0}""
  env:
    DOTNET_ROOT: C:\Users\runneradmin\AppData\Local\Microsoft\dotnet
Cannot perform a cyclic copy
0 File(s) copied
Error: Process completed with exit code 4.
```

Moreover, this workaround should no longer be required, see https://github.com/actions/setup-dotnet/issues/25